sonar.projectKey=auth_service
sonar.projectName=auth_service
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/.git/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out